name: periodtracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.3+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_mobile_ads: ^6.0.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  change_app_package_name: ^1.4.0
  package_info_plus: ^8.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/splash.png
  - assets/icon.png
  - assets/women.png
  - assets/profile_pics/
